global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/uptime-mesh/monitoring/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 127.0.0.1:9093

scrape_configs:
  - job_name: uptimemesh
    metrics_path: /metrics
    static_configs:
      - targets:
          - 127.0.0.1:8010

  - job_name: node_exporter
    static_configs:
      - targets:
          - 127.0.0.1:9100
